---
- name: initial setup
  hosts: devcon-server
  user: root

  roles:
    - prepare
    - passenger
    - php-fpm
    - mysql
    - security

- name: non-sudo setup
  hosts: devcon-server
  remote_user: deploy

  roles:
    - piwik

- name: finish setup
  hosts: devcon-server
  user: root
  roles:
    - finish
