---
- name: initial setup
  hosts: devcon-server
  # user: root
  remote_user: ubuntu
  sudo: yes
  roles:
    - common
    - users
    - passenger
    - php-fpm
    - mysql

- name: non-sudo setup
  hosts: devcon-server
  # user: root
  remote_user: deploy

  roles:
    - piwik

- name: finish setup
  hosts: devcon-server
  # user: root
  remote_user: ubuntu
  sudo: yes
  roles:
    - finish
