---
- name: deploy ssh public key to root
  authorized_key: user="root" key="{{ my_pub_key }}"

- name: create ssh user group
  group: name="sshusers" state=present

- name: add root to ssh group
  user: name=root groups="sshusers" append=yes

- name: add root to ssh group
  user: name=deploy groups="sshusers" append=yes

- name: Strict SSH access
  lineinfile: >
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
    validate='/usr/sbin/sshd -t -f %s'
  with_items:
    - { key: 'PermitRootLogin',        value: 'without-password'}
    - { key: 'PasswordAuthentication', value: 'no'}
    - { key: 'AllowGroups',            value: "sshusers"}
    - { key: 'MaxAuthTries',           value: "5"}
    - { key: 'LoginGraceTime',         value: "60"}
    - { key: 'MaxSessions',            value: "5"}
    - { key: 'MaxStartups',            value: "10:30:60"}
  notify: restart sshd

- name: Configure firewall for SSH
  ufw: rule=allow name=OpenSSH
     
- name: Enable firewall 
  ufw: state=enabled 

- name: reboot
  command: reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: wait for reboot to finish
  local_action: wait_for host={{ inventory_hostname }} state=started
  sudo: false

