---
- name: add brightbox ruby package repo
  apt_repository: repo='ppa:brightbox/ruby-ng' update_cache=no

- name: update apt cache
  apt: upgrade=dist update_cache=yes

- name: install required packages
  apt: pkg="{{ item }}" state=latest
  with_items:
    - git-core
    - build-essential
    - libssl-dev
    - libcurl4-openssl-dev
    - libpcre3-dev
    - zlib1g-dev
    - ruby2.2
    - ruby2.2-dev
    - libruby2.2
    - htop
    - fail2ban
    - postfix
    - nginx
    - nodejs
    - imagemagick
    - libmagickwand-dev

- name: install bundler
  command: /usr/bin/gem2.2 install bundler --no-ri --no-rdoc

- name: add deploy user
  user: name=deploy shell=/bin/bash

- name: upload and extract backup
  unarchive: src=./backup.tar.bz2 dest=/

- name: change apps permisions
  file: path=/home/deploy/apps owner=deploy group=deploy recurse=yes

- name: change ssh permisions
  file: path=/home/deploy/.ssh owner=deploy group=deploy mode=600 recurse=yes
- file: path=/home/deploy/.ssh mode=700

