---
- name: get passengeer PGP keys
  apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7

- name: add passenger source repo
  template: src=passenger.list dest=/etc/apt/sources.list.d/passenger.list owner=root mode=0644

- name: update apt cache
  apt: update_cache=yes

- name: install passenger and nginx
  apt: pkg="{{ item }}" state=latest
  with_items:
    - nginx-extras
    - passenger

- name: add base nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: add default (devcon.ph) conf
  template: src=default dest=/etc/nginx/sites-available/default

- name: add beta conf
  template: src=beta dest=/etc/nginx/sites-available/beta
#- file: src=/etc/nginx/sites-available/beta dest=/etc/nginx/sites-enabled/beta state=link

- name: add piwik conf
  template: src=piwik dest=/etc/nginx/sites-available/piwik
- file: src=/etc/nginx/sites-available/piwik dest=/etc/nginx/sites-enabled/piwik state=link

- name: add summit and api conf
  template: src=summit dest=/etc/nginx/sites-available/summit
- file: src=/etc/nginx/sites-available/summit dest=/etc/nginx/sites-enabled/summit state=link

